<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// admin/ads/print_report.php
require_once __DIR__ . '/../../auth/Auth.php';
require_once __DIR__ . '/../../auth/db.php';

if (!Auth::isLoggedIn() || $_SESSION['role'] !== 'admin') {
    die('Unauthorized');
}

$start = $_GET['start_date'] ?? date('Y-m-d');
$end = $_GET['end_date'] ?? date('Y-m-d');

// Convert to datetime
$tsStart = $start . ' 00:00:00';
$tsEnd = $end . ' 23:59:59';

// Fetch Data
$user = Auth::user();
$userEmail = $user ? $user['email'] : 'Unknown User';

$where = " WHERE created_at BETWEEN ? AND ? ";
$mParams = [$tsStart, $tsEnd];
$mTypes = "ss";

$targetAdId = isset($_GET['ad_id']) ? (int)$_GET['ad_id'] : null;

if ($targetAdId) {
    $where .= " AND ad_id = ? ";
    $mParams[] = $targetAdId;
    $mTypes .= "i";
}

// Metrics
// We fetch single row, but statement might remain open.
// Wrap in block to be safe or assuming one-shot is fine if we proceed?
// Actually if "Sync" issue happened at line 63, it means previous queries at 41/42 weren't closed?
// Or line 61's query?
// Line 61: $resT = DB::query(...)
// Line 63: while(...)
// If 41/42 caused it, error would be at 61.
// If error is at 63, it's inside the loop?
// "Commands out of sync ... print_report.php:63"
// Line 63 in file is `while($row = $resT->get_result()->fetch_assoc())`
// The calls to `get_result()` REPEATEDLY is the issue.

$imp = DB::query("SELECT COUNT(*) as c FROM ad_impressions" . $where, $mParams, $mTypes)->get_result()->fetch_assoc()['c'];
$clk = DB::query("SELECT COUNT(*) as c FROM ad_clicks" . $where, $mParams, $mTypes)->get_result()->fetch_assoc()['c'];
$ctr = ($imp > 0) ? ($clk / $imp) * 100 : 0;


// Table Data
$adsList = [];

$sql = "SELECT a.ad_id, a.ad_title, a.ad_type, a.status FROM ads a";
$params = [];
$types = "";

if ($targetAdId) {
    $sql .= " WHERE a.ad_id = ?";
    $params[] = $targetAdId;
    $types .= "i";
}

$resT = DB::query($sql, $params, $types);
if($resT) {
    $resultSet = $resT->get_result();
    while($row = $resultSet->fetch_assoc()) $adsList[] = $row;
}

$table = [];
foreach($adsList as $currAd) {
    $i = DB::query("SELECT COUNT(*) as c FROM ad_impressions WHERE ad_id = ? AND created_at BETWEEN ? AND ?", [$currAd['ad_id'], $tsStart, $tsEnd], "iss")->get_result()->fetch_assoc()['c'];
    if ($i == 0 && $currAd['status'] !== 'active') continue; 
    $c = DB::query("SELECT COUNT(*) as c FROM ad_clicks WHERE ad_id = ? AND created_at BETWEEN ? AND ?", [$currAd['ad_id'], $tsStart, $tsEnd], "iss")->get_result()->fetch_assoc()['c'];
    
    $currAd['impressions'] = $i;
    $currAd['clicks'] = $c;
    $currAd['ctr'] = ($i > 0) ? ($c / $i) * 100 : 0;
    $table[] = $currAd;
}
usort($table, function($a, $b) { return $b['impressions'] - $a['impressions']; });

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ads Report - <?php echo $start; ?> to <?php echo $end; ?></title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @media print {
            body { -webkit-print-color-adjust: exact; }
            .no-print { display: none; }
        }
    </style>
</head>
<body class="bg-white text-slate-800 p-8">

    <div class="flex justify-between items-end mb-8 border-b-2 border-slate-800 pb-4">
        <div>
            <h1 class="text-3xl font-bold text-slate-900">VDraw Ads Report</h1>
            <div class="text-slate-500 mt-1">Generated by <?php echo htmlspecialchars($userEmail); ?> on <?php echo date('Y-m-d H:i'); ?></div>
        </div>
        <div class="text-right">
            <div class="text-sm font-bold text-slate-600 uppercase tracking-widest">Period</div>
            <div class="text-xl font-mono"><?php echo $start; ?> <span class="text-slate-400 mx-1">to</span> <?php echo $end; ?></div>
        </div>
    </div>

    <!-- Summary Cards -->
    <div class="grid grid-cols-3 gap-8 mb-8">
        <div class="bg-slate-50 p-6 rounded border border-slate-200">
            <div class="text-xs uppercase font-bold text-slate-500">Total Impressions</div>
            <div class="text-4xl font-bold text-slate-900 mt-2"><?php echo number_format($imp); ?></div>
        </div>
        <div class="bg-slate-50 p-6 rounded border border-slate-200">
            <div class="text-xs uppercase font-bold text-slate-500">Total Clicks</div>
            <div class="text-4xl font-bold text-slate-900 mt-2"><?php echo number_format($clk); ?></div>
        </div>
        <div class="bg-slate-50 p-6 rounded border border-slate-200">
            <div class="text-xs uppercase font-bold text-slate-500">Avg. CTR</div>
            <div class="text-4xl font-bold text-slate-900 mt-2"><?php echo number_format($ctr, 2); ?>%</div>
        </div>
    </div>

    <!-- Table -->
    <h2 class="text-xl font-bold mb-4">Ad Campaign Performance</h2>
    <table class="w-full text-left text-sm border-collapse">
        <thead>
            <tr class="border-b-2 border-slate-800 text-slate-600 uppercase text-xs">
                <th class="py-2">Campaign</th>
                <th class="py-2">Type</th>
                <th class="py-2 text-center">Status</th>
                <th class="py-2 text-right">Impressions</th>
                <th class="py-2 text-right">Clicks</th>
                <th class="py-2 text-right">CTR</th>
            </tr>
        </thead>
        <tbody class="divide-y divide-slate-200">
            <?php foreach($table as $row): ?>
            <tr>
                <td class="py-3 font-bold"><?php echo htmlspecialchars($row['ad_title']); ?> <span class="font-normal text-slate-400 text-xs ml-2">#<?php echo $row['ad_id']; ?></span></td>
                <td class="py-3 text-slate-500 uppercase text-xs"><?php echo $row['ad_type']; ?></td>
                <td class="py-3 text-center">
                    <span class="px-2 py-1 rounded text-xs font-bold 
                        <?php echo $row['status'] === 'active' ? 'bg-green-100 text-green-700' : ($row['status'] === 'completed' ? 'bg-blue-100 text-blue-700' : 'bg-yellow-100 text-yellow-700'); ?>">
                        <?php echo strtoupper($row['status']); ?>
                    </span>
                </td>
                <td class="py-3 text-right font-mono"><?php echo number_format($row['impressions']); ?></td>
                <td class="py-3 text-right font-mono"><?php echo number_format($row['clicks']); ?></td>
                <td class="py-3 text-right font-mono font-bold"><?php echo number_format($row['ctr'], 2); ?>%</td>
            </tr>
            <?php endforeach; ?>
            <?php if(empty($table)): ?>
            <tr><td colspan="6" class="py-8 text-center text-slate-500 italic">No data found for this period.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="mt-12 text-center text-xs text-slate-400 border-t border-slate-200 pt-4">
        &copy; <?php echo date('Y'); ?> VDraw Anti-Automation System. Internal Report.
    </div>

    <script>
        window.print();
    </script>
</body>
</html>
